[workspace]
members = [
    "eduverse-anchor/programs/*",
    "eduverse-anchor/anchor-wasm",
    "eduverse-frontend",
]

resolver = "2"


[workspace.dependencies]
eduverse-contract = { path = "eduverse-anchor/programs/eduverse-contract", default-features = false, features = [
    "wasm",
] }
